server:
  port: 8090
spring:
  jpa:
    open-in-view:
      exclude-patterns: /chat/writeMessage, /chat/messages
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true